@url = http://localhost:8080

###
POST {{url}}/create_account HTTP/1.1
Content-Type: application/json

{
  "username":"BLowe94",
  "email": "BLowe94@gmail.com",
  "password":"P@ssword",
  "roles": "ADMIN"
}

###
POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
  "username":"BLowe",
  "password":"P@ssword1"
}


###
GET https://sportspage-feeds.p.rapidapi.com/games?league=MLB HTTP/1.1
Content-Type: application/json
X-RapidAPI-Key: 0996ff329emshe772ea55758fe91p185bdejsn54b9509c4a00
X-RapidAPI-Host: sportspage-feeds.p.rapidapi.com

###
ws://localhost:8080/live-scores