@url = http://localhost:8080

###
POST {{url}}/create_account HTTP/1.1
Content-Type: application/json

{
  "username":"BLowe94",
  "email": "BLowe94@gmail.com",
  "password":"P@ssword",
  "roles": "ADMIN"
}

###
POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
  "username":"BLowe",
  "password":"P@ssword1"
}


###
GET https://sportspage-feeds.p.rapidapi.com/games?league=MLB HTTP/1.1
Content-Type: application/json
X-RapidAPI-Key: 0996ff329emshe772ea55758fe91p185bdejsn54b9509c4a00
X-RapidAPI-Host: sportspage-feeds.p.rapidapi.com

###
GET http://localhost:8080/api/games?league=MLB&date=2024-05-13
Content-Type: application/json

###
POST {{url}}/api/notifications HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsaXZlLXNjb3JlLWh1YiIsInN1YiI6IkJMb3dlOTQiLCJhcHBfdXNlcl9pZCI6MSwiZW1haWwiOiJCTG93ZTk0QGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiVVNFUiIsImV4cCI6MTcyNDE3MTI0NX0.JhCKHe4CvUN1nwCOXEEzzkh9Wckm86_D89L3ykITZL4

{
  "user_id": 1,
  "game_id": {
    "game_id": 310499
  },
  "notification_type": "PRE_GAME",
  "notification_time": "2024-08-20T15:00:00"
}

###

GET {{url}}/api/notifications/user/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsaXZlLXNjb3JlLWh1YiIsInN1YiI6IkJMb3dlOTQiLCJhcHBfdXNlcl9pZCI6MSwiZW1haWwiOiJCTG93ZTk0QGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiVVNFUiIsImV4cCI6MTcyNDE3MTI0NX0.JhCKHe4CvUN1nwCOXEEzzkh9Wckm86_D89L3ykITZL4


###
POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
  "username":"BLowe94",
  "password":"P@ssword1"
}


###
POST {{url}}/api/notifications HTTP/1.1
Content-Type: application/json

{
  "user_id": 1,
  "game_id": 310464,
}

###

DELETE {{url}}/api/notifications?user_id=1&game_id=310499 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsaXZlLXNjb3JlLWh1YiIsInN1YiI6IkJMb3dlOTQiLCJhcHBfdXNlcl9pZCI6MSwiZW1haWwiOiJCTG93ZTk0QGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiVVNFUiIsImV4cCI6MTcyNDE3MTI0NX0.JhCKHe4CvUN1nwCOXEEzzkh9Wckm86_D89L3ykITZL4
